name: Test requirements
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'charts/**'
      - 'mkdocs.yml'
      - 'docker-jans-**/README.md'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'charts/**'
      - 'mkdocs.yml'
      - 'docker-jans-**/README.md'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g."v1.1.6")'
        default: "nightly"
        required: false
permissions:
  contents: read

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Python 3.10
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: docs/requirements.txt

      - name: Install dependencies
        run: |
          pip install --require-hashes -r docs/requirements.txt
          cp mkdocs.yml ../
